name: Build and Deploy Static Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: ${{ github.actor == 'SyedJasmine1991' }}
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js 16.18.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.0

      - name: Use Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 🔧 Install Dependencies & Build
        run: |
          npm install --force
          npm run build

          # ✅ Move contents from build/ to project root
          shopt -s dotglob
          mv build/* . || true
          mv build/.* . || true
          rm -rf build

      - name: 🔑 Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          # Remove ssh-keygen step as it's not needed
          echo "Host *
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null" > ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: 🔍 Test SSH Connection
        run: |
          if ! ssh -i ~/.ssh/authorized_keys -o BatchMode=yes ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "echo 'Connection successful'"; then
            echo "SSH connection failed"
            exit 1
          fi

      - name: 📤 Deploy to aaPanel
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key_path: ~/.ssh/authorized_keys
          port: 22
          source: "./*"
          target: "/www/wwwroot/arconsultancy.unitdtechnologies.com/"
          debug: true
          strip_components: 0
          timeout: "600s"
          rm: false
          overwrite: true
